name: Area selection
type: boilerplate
regex: |
  ^\\[ ?x ?\\] ?Configuration Infrastructure
  \\[ ?x ?\\] ?Docs
  \\[ ?x ?\\] ?Installation
  \\[ ?x ?\\] ?Networking
  \\[ ?x ?\\] ?Performance and Scalability
  \\[ ?x ?\\] ?Policies and Telemetry
  \\[ ?x ?\\] ?Security
  \\[ ?x ?\\] ?Test and Release
  \\[ ?x ?\\] ?User Experience
  \\[ ?x ?\\] ?Developer Infrastructure
